#!/bin/bash

# Search if .Net Core installed
which dotnet > /dev/null
if [[ $? -ne 0 ]]; then
    echo ".Net Core Runtime is missing, please install from https://dotnet.microsoft.com/download"
    exit 2
fi

# Check .Net Core version
DOTNETVER=$( dotnet --version | grep -Po -m 1 '^\d+.\d+' )
if [[ "$DOTNETVER" == "2.1" ]]; then
    echo "Another version of .Net Core Runtime is installed, please install version 2.1 from https://dotnet.microsoft.com/download"
    exit 3
fi

# All good run aggregator forwarding any parameter
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
dotnet "$SCRIPTPATH/aggregator-cli.dll" $@
