on:
  push:
    paths:
    - '.github/workflows/**'
    - 'src/**'
  pull_request:
    paths:
    - '.github/workflows/**'
    - 'src/**'

env:
  map_os_to_rid: '{"ubuntu-latest":"linux-x64", "windows-latest":"win-x64"}'
  docker_repo: giuliov/aggregator

jobs:
  push_image_to_registry:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: echo ${{ fromJSON(env.map_os_to_rid)[matrix.os] }}
    - name: Build and push Docker ${{ matrix.os }} image
      uses: docker/build-push-action@v1
      with:
        path: src/.
        dockerfile: src/${{ fromJSON(env.map_os_to_rid)[matrix.os] }}.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.docker_repo }}
        cache_froms: mcr.microsoft.com/dotnet/core/sdk:3.1,mcr.microsoft.com/dotnet/core/aspnet:3.1
        add_git_labels: true
        tags: ${{ env.VERSION }}-${{ fromJSON(env.map_os_to_rid)[matrix.os] }}
      if: ${{ false }}

  push_manifest_to_registry:
    runs-on: ubuntu-latest
    needs: push_image_to_registry
    steps:
    - run: |
        docker manifest create ${{ env.docker_repo }}:latest  --amend ${{ env.docker_repo }}:win-x64  --amend ${{ env.docker_repo }}:linux-x64
        docker manifest push ${{ env.docker_repo }}:latest
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
